### ISSUE TITLE
Bank/block mapping incorrect?

### ISSUE THREAD

**Issue by srett** [tuxuser/xbit_flasher-xbox#2]
So I was flashing and reading back BIOS images all evening until all banks could be read back and would result in exactly the same binary as flashed:

Formatted chip in layout 3 (1M, 512k, 256k, 256k)
Flashed a BIOS to banks 1, 3 and 4.
Read back all three and made sure the match exactly the original files.

Finally got to boot the xbox up, only to discover the following:

BIOS 1 (all switches off) doesn't boot
BIOS 3 (off on off) doesn't boot
BIOS 4 (on on off) DOES boot, but it's actually the one I flashed to bank 3!

I reconnected the chip, read back all banks again and sure enough, they were still all intact. For now, I just flashed my preferred BIOS to bank 3 and set the dip switches on the chip to bank 4, but I'd actually like to use the 1M BIOS too at some point. :-)
So either I'm going insane or the util isn't writing stuff to where the chip actually expects them to be. Any ideas?

**Comment by tuxuser** [comment]
I took it 1:1 from the disassembly, but I can look into it again

**Comment by srett** [comment]
No hurry though, tinkering with the old xbox is one of too many side projects...

Thanks for this awesome work in any case, just before I found it I thought it would be cool to reverse engineer the protocol and build an open source tool, and then saw that actually someone did that not too long ago. :-)

Is it possible that there are different revisions of this chip and that the software might do some checking? All I could find is that there seems to be a v1.0 and v1.5, and according to the little information I could find online mine should be a v1.0 (v1.5 has the version printed on the USB PCB). Not that I really expect it to be that sophisticated considering the overall quality of that chip...
