### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by tengzl33t** [tuxuser/xbit_flasher-xbox#4]
Installed hidapi with brew on Fedora, but can't do "make -f Makefile" writes:

```
g++ -c -g -Wall -I /home/linuxbrew/.linuxbrew/Cellar/hidapi/0.10.1/include main.cpp
make: g++: No such file or directory
make: *** [Makefile:12: main.o] Error 127
```
Please, help.

**Comment by tuxuser** [comment]
Try this

```
sudo dnf install make automake gcc gcc-c++
```

**Comment by tengzl33t** [comment]
automake installed, but now it can't find -lhidapi (/home/linuxbrew/.linuxbrew/bin/ld: cannot find -lhidapi), hidapi in brew is installed

**Comment by tuxuser** [comment]
In Makefile, verify that `CFLAGS` and `LDFLAGS` are correct

**Comment by tengzl33t** [comment]
Maybe something with path, but it should be correct, only versions are different (your make has 0.8.1-rc1, latest from brew is 0.10.1).

![изображение](https://user-images.githubusercontent.com/10462726/131191621-ae8dc058-14fe-46d9-b29c-21ededbd3e75.png)

lib folder content:
![изображение](https://user-images.githubusercontent.com/10462726/131191787-3eec643e-6892-4f48-ade5-2c963bf92d6d.png)

**Comment by tuxuser** [comment]
Change

`LIBS = -lhidapi`

To

`LIBS = -lhidapi-libusb`

**Comment by tengzl33t** [comment]
compiled, thanks. [xbit_flasher.zip](https://github.com/tuxuser/xbit_flasher-xbox/files/7069621/xbit_flasher.zip)
going to test with xbit 1.0 chip.
